name: meamore
description: "me amore employees monitor"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  meamore_shared:
    path: ../../packages/meamore_shared

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.0
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  excel: ^4.0.2
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  cross_file: ^0.3.4+2
  local_auth: ^3.0.0
  flutter_native_contact_picker: ^0.0.11
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
